const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "238163206711";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_04_46_09_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjQyLFxuICAgICAgICAyMjgsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTgyLFxuICAgICAgICAzNyxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDE0NSxcbiAgICAgICAgODYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNjYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNixcbiAgICAgICAgMTA4LFxuICAgICAgICAxODUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTYwLFxuICAgICAgICA1MyxcbiAgICAgICAgMTM5LFxuICAgICAgICAxNzQsXG4gICAgICAgIDE4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMzEsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjQ4LFxuICAgICAgICA3NSxcbiAgICAgICAgNDAsXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzOCxcbiAgICAgICAgNzAsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNDksXG4gICAgICAgIDQ5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjE4LFxuICAgICAgICAxODksXG4gICAgICAgIDU2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTU0LFxuICAgICAgICAxNjQsXG4gICAgICAgIDY4LFxuICAgICAgICAxNDYsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjUwLFxuICAgICAgICAyMjMsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDIyLFxuICAgICAgICAxNTUsXG4gICAgICAgIDg2LFxuICAgICAgICA3NCxcbiAgICAgICAgMCxcbiAgICAgICAgMzgsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNjMsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDgsXG4gICAgICAgIDk2LFxuICAgICAgICA3NixcbiAgICAgICAgMTYxLFxuICAgICAgICA0NixcbiAgICAgICAgMSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNzQsXG4gICAgICAgIDE2NCxcbiAgICAgICAgODMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgOTksXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNDQsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTI3LFxuICAgICAgICA5MixcbiAgICAgICAgOTgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjM5LFxuICAgICAgICAxOTIsXG4gICAgICAgIDEwOCxcbiAgICAgICAgOTcsXG4gICAgICAgIDg1LFxuICAgICAgICA0NyxcbiAgICAgICAgMjAzLFxuICAgICAgICAyMDAsXG4gICAgICAgIDE4NCxcbiAgICAgICAgODQsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTE1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExNixcbiAgICAgICAgMTMxLFxuICAgICAgICAyMTAsXG4gICAgICAgIDExNixcbiAgICAgICAgNDEsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTc0LFxuICAgICAgICA2MCxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNTYsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDE5LFxuICAgICAgICA3NCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxNDgsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxMTgsXG4gICAgICAgIDUsXG4gICAgICAgIDIxNixcbiAgICAgICAgODYsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTE4LFxuICAgICAgICAzNyxcbiAgICAgICAgMjE4LFxuICAgICAgICAzOSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMTUsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNjFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDg4LFxuICAgICAgICAxNjksXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjI1LFxuICAgICAgICA4OCxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMTAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjI4LFxuICAgICAgICAzNCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxODMsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjI0LFxuICAgICAgICAxNTcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgNzgsXG4gICAgICAgIDM4LFxuICAgICAgICA5LFxuICAgICAgICA1NCxcbiAgICAgICAgMzUsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMDAsXG4gICAgICAgIDYyLFxuICAgICAgICA5NyxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjI2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDExMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMixcbiAgICAgICAgMjMxLFxuICAgICAgICAxOTIsXG4gICAgICAgIDExNCxcbiAgICAgICAgNjgsXG4gICAgICAgIDIzMixcbiAgICAgICAgODEsXG4gICAgICAgIDIzLFxuICAgICAgICA4OSxcbiAgICAgICAgMTczLFxuICAgICAgICAyMzgsXG4gICAgICAgIDM4LFxuICAgICAgICAxMixcbiAgICAgICAgMTAxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNTYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTg1LFxuICAgICAgICA1MyxcbiAgICAgICAgMjYsXG4gICAgICAgIDI2LFxuICAgICAgICAxMTgsXG4gICAgICAgIDY0LFxuICAgICAgICAzNyxcbiAgICAgICAgMjM1LFxuICAgICAgICAwLFxuICAgICAgICA4OCxcbiAgICAgICAgOCxcbiAgICAgICAgMCxcbiAgICAgICAgNDEsXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICA3NixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICA2OFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDExMixcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAzNVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwOCxcbiAgICAgICAgODcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjE3LFxuICAgICAgICAyOSxcbiAgICAgICAgNzAsXG4gICAgICAgIDcxLFxuICAgICAgICAxOSxcbiAgICAgICAgMzQsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNjcsXG4gICAgICAgIDMwLFxuICAgICAgICA5NixcbiAgICAgICAgNDEsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTMwLFxuICAgICAgICAzNixcbiAgICAgICAgNzAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA3OSxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTU2LFxuICAgICAgICA3OCxcbiAgICAgICAgNDgsXG4gICAgICAgIDEzLFxuICAgICAgICAxMTUsXG4gICAgICAgIDg1LFxuICAgICAgICA5MCxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTQ5LFxuICAgICAgICA4MCxcbiAgICAgICAgNDUsXG4gICAgICAgIDIzNixcbiAgICAgICAgNjUsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTIxLFxuICAgICAgICAxODEsXG4gICAgICAgIDIsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTM0LFxuICAgICAgICAxNSxcbiAgICAgICAgMjM5LFxuICAgICAgICA5OCxcbiAgICAgICAgNzIsXG4gICAgICAgIDQsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjQyLFxuICAgICAgICA3OCxcbiAgICAgICAgODMsXG4gICAgICAgIDE5NixcbiAgICAgICAgNDcsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNDQsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjE0LFxuICAgICAgICA0OCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE2MSxcbiAgICAgICAgNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogNTksXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiTXpKL1hSK2hRZy95Zk83VHdGNDk1MERqM0RsR3JZM1U4dG1Pc1VUM3RKZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MTYzMjA2NzExQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyODg4ODVGN0YwMDRDOTgwN0VFRjdFQzIzNUY3MzlGNFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjcyMzk2MTRcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiRFpKaTdjUEFTQ09OWHEtTlplMVQyUVwiLFxuICBcInBob25lSWRcIjogXCJiYTYzZDk2YS1jZDhkLTQ2ZDYtYWJmOS02NmZiMjAzZTk3NzdcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNzAsXG4gICAgICAyNCxcbiAgICAgIDUwLFxuICAgICAgMjIxLFxuICAgICAgMTAwLFxuICAgICAgMyxcbiAgICAgIDE2NixcbiAgICAgIDEsXG4gICAgICAxNjIsXG4gICAgICAzNSxcbiAgICAgIDIyOCxcbiAgICAgIDE2NSxcbiAgICAgIDQxLFxuICAgICAgMTQyLFxuICAgICAgMTk3LFxuICAgICAgMTkwLFxuICAgICAgMTEzLFxuICAgICAgMTMxLFxuICAgICAgMTgsXG4gICAgICAxNDFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTMyLFxuICAgICAgMTM5LFxuICAgICAgMTIzLFxuICAgICAgMTI4LFxuICAgICAgMTk5LFxuICAgICAgNyxcbiAgICAgIDIwMCxcbiAgICAgIDEyMSxcbiAgICAgIDUxLFxuICAgICAgOTUsXG4gICAgICA3MCxcbiAgICAgIDMwLFxuICAgICAgMjAsXG4gICAgICAyMjMsXG4gICAgICA0LFxuICAgICAgNjgsXG4gICAgICAyMjYsXG4gICAgICA3MyxcbiAgICAgIDE2NixcbiAgICAgIDQzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlo2UVQ2MjdWXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ4MTYzMjA2NzExOjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJGb29kIENvbW1vZGl0aWVzXCIsXG4gICAgXCJsaWRcIjogXCIxNDI4OTgyNTk5Njg2MzozQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0l2TzBMY0JFTFdyenJjR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwieHlDQWw3V0ZwcUxaamdmVlErUTJJYmxmWXNhSGpVL3pxU2pLSzFaRzkxMD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJQeC9rT1oxNW5pSHd3U0RYdGhnK2VRVG52dGpLQWhURW1VNGZLeGxwYjZPSGRXWVdqMmdhdFRUOWZGeEE2Y2w1MThOd0VEcEZRSDV1RjlBeWwydTVEZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJZMkU3REtMNzU2Q3JLYVJKN3B1TUYxWkd3aFNndWRWSURzMDgvZE56dmdWWWFFWExoRkRZUUdWR0JBanVYZmIyNHRnK09BWitPMjFJRFhFOEZuaDdDZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MTYzMjA2NzExOjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICA3LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA5M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3MjM5NjEwLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRHVxXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEdXEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJOb1QrNFF4UngxQm9oYmo4N2phemQ3OWdHRWhRUHhjSWIvZ3hFZEpPZWFjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4NTA5OTUzMSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI0OTEzMjUwODgxXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
